title = "jocmp"
baseURL = "https://jocmp.com/"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
pluralizeListTitles = false
rssLimit = 25

[params]
  description = ""
  about_me = "Web dev with a heart for mobile apps. Currently building Capy Reader."
  ogimage = "/avatar.jpg"
  github_username = "https://github.com/jocmp"
  mastodon_username = "https://mastodon.social/@_jocmp"

[params.author]
  name = "Josiah Campbell"
  avatar = "/avatar.jpg"

[taxonomies]
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "static/uploads"
  target = "assets/uploads"

[[module.mounts]]
  source = "static"
  target = "static"

[mediaTypes."application/json"]
  suffixes = ["json"]

[outputFormats.RSS]
  baseName = "feed"

[outputFormats.JSON]
  baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
